import React, { useEffect, useState } from 'react'
import { useRouter } from 'next/router'
import Head from 'next/head'
import Image from 'next/Image'
import Link from 'next/link'
import headImg from '../../public/Images/collections.png'
import styles from '../../styles/NewArrivals.module.css'
import Product from '../../components/product'


const slug = () => {
  const [prods, setProds] = useState([]);
  const [collection, setCollection] = useState('');
  const router = useRouter()
  const query = router.query.slug
  useEffect(() => {
    console.log(query)
    fetch(`${process.env.NEXT_PUBLIC_HOST}collections/${query}`).then((a) => {
      return a.json();
    })
      .then((parsed) => {
        setProds(parsed);
        setCollection(query)
      })
    console.log("useEffect is running")
  }, [router])

  return (
    <>
      <Head>
        <title>Earthie Fashion - {collection} Collections</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="row">
        <div className="col-12 h-25" >
          <Image src={headImg} fill alt='Collections' className={styles.headerImg + ' '} />
        </div>

        <div className="col-12">

          <div className="container mt-3">
            <div className="row">
              {prods.map((slide) => {
                if (slide.is_published) {
                  return (
                    <Link href={`col/${slide.id}`} key={slide.id} className="col-12 col-lg-3 col-md-4 col-sm-6 my-3 d-flex justify-content-center my-3">
                      <div key={slide.id}>
                        <Product productId={slide.id} productName={slide.prodcutName} productPrice={slide.productPrice} productImage={slide.productImage} />
                      </div>
                    </Link>
                  )
                }
              })}
            </div>
          </div>
        </div>
      </div>
    </>
  )
}

export default slug