import React, { useEffect, useState } from 'react'
import { useRouter } from 'next/router'
import Head from 'next/head'
import Image from 'next/Image'
import Link from 'next/link'
import styles from '../../styles/ProdPage.module.css'
import axios from 'axios'

const slug = () => {
  const [prods, setProds] = useState([]);
  const [prodName, setProdName] = useState('');
  const [img, setImg] = useState();
  const router = useRouter()
  const query = router.query.slug
  useEffect(() => {
    fetch(`${process.env.NEXT_PUBLIC_HOST}product/${query}`).then((a) => {
      return a.json();
    })
      .then((parsed) => {
        setProds(parsed);
        setProdName(parsed[0].prodcutName)
        setImg(parsed[0].productImage)
      })
  }, [router])

  return (
    <>
      <Head>
        <title>Earthie Fashion : {prodName}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {prods.map((slide) => {
        if (slide.is_published) {
          return (
            <div className="container pt-5" key={slide.id}>
              <div className={styles.mainRow + " row pt-5"}>
                <div className="col-12 col-lg-7 col-md-12">
                  <div className="row p-0">
                    <div className="col-9 col-lg-9 col-md-9 p-0">
                      <Image src={`${process.env.NEXT_PUBLIC_MEDIA_URL}` + img} className={styles.prodImage} width={1080} height={1080} />
                    </div>
                    <div className={styles.rightBar + " col-3 col-lg-3 col-md-3"}>
                      <div className={styles.photoBar + " row"}>
                        <div className={styles.extraProductImageWrapper + " col-12"}>
                          <Image src={`${process.env.NEXT_PUBLIC_MEDIA_URL}` + slide.productImage} onClick={(() => {
                            setImg(slide.productImage)
                          })} className={styles.extraProductImage} width={320} height={320} />
                        </div>

                        <div className={styles.extraProductImageWrapper + " col-12"}>
                          <Image src={`${process.env.NEXT_PUBLIC_MEDIA_URL}` + slide.miscImage1} onClick={(() => {
                            setImg(slide.miscImage1)
                          })} className={styles.extraProductImage} width={320} height={320} />
                        </div>
                        <div className={styles.extraProductImageWrapper + " col-12"}>
                          <Image src={`${process.env.NEXT_PUBLIC_MEDIA_URL}` + slide.miscImage2} onClick={(() => {
                            setImg(slide.miscImage2)
                          })} className={styles.extraProductImage} width={320} height={320} />
                        </div>

                      </div>
                    </div>
                  </div>
                </div>
                <div className="col-12 col-lg-5 col-md-12 mt-3 mt-lg-0 mt-md-0 mt-sm-3">
                  <p className={styles.prodName + " mb-0"}>
                    {slide.prodcutName}
                  </p>

                  <p className={styles.prodPrice + " mx-1 mt-1  mt-md-3 mt-sm-1 mb-0"}>
                    ₹{slide.productPrice}
                  </p>

                  <div className="sizesWrapper  mt-2 mt-lg-4 mt-md-4 mt-sm-2 mx-1">
                    <p className={styles.prodSize + " mb-1"}>
                      Select a Size
                    </p>
                    <select className={styles.sizeSelect + " form-select w-auto"} aria-label="Default select example">
                      <option value="S">S - small</option>
                      <option value="M">M - medium</option>
                      <option value="L">L - large</option>
                      <option value="XL">XL - extra large</option>
                    </select>
                  </div>

                  <div className="sizesWrapper mt-2 mt-lg-4 mt-md-4 mt-sm-2 mx-1">
                    <p className={styles.prodSize + " mb-1 mx-1"}>
                      Material & Care
                    </p>
                    <div className="mx-1">
                      <p className="careText mb-0 mx-0">{slide.material}</p>
                      <p className="careText mb-0 mx-0">{slide.care}</p>
                    </div>
                  </div>

                  <div className="btnWrapper px-2 mt-3">
                    <div className={styles.addBtn + " col-12 py-1 mt-1 pb-2"}>
                      <p className='d-flex align-items-center mb-0' > Add To Cart </p>
                    </div>
                  </div>


                </div>
              </div>
            </div>
          )
        }
      })}

    </>
  )
}

export default slug