import React, { useEffect, useState } from 'react'
import Head from 'next/head'
import Image from 'next/Image'
import headImg from '../public/Images/cart.png'
import styles from '../styles/WishList.module.css'
import Product from '../components/product'
import axios from 'axios'

function cart() {
    const [prods, setProds] = useState([])
    const [loaded, setLoaded] = useState(false)
    useEffect(() => {
        const data = JSON.parse(localStorage.getItem('cart'))
        setProds(data)
    }, [])
    return (
        <>
            <Head>
                <title>Earthie Fashion - Collections</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="row">
                <div className="col-12 h-25" >
                    <Image src={headImg} fill alt='Collections' className={styles.headerImg + ' '} />
                </div>

                <div className="col-12">
                    <div className="container mt-3">
                        <div className="row">
                            {prods.map((slide) => {
                                    return (
                                        <div key={slide.id} className="col-12 col-lg-3 col-md-4 col-sm-6 my-3 d-flex justify-content-center my-3">
                                            <Product productId={slide.id} productName={slide.prodName} productPrice={slide.prodPrice} productImage={slide.prodImage} />
                                        </div>
                                    )
                                })
                            }
                        </div>
                    </div>
                </div>
            </div>
        </>
    )
}

export default cart