import React, { useEffect, useState } from 'react'
import Head from 'next/head'
import Image from 'next/Image'
import Link from 'next/link'
import headImg from '../public/Images/collections.png'
import styles from '../styles/NewArrivals.module.css'
import CollectionCard from '../components/collectioncard'
import axios from 'axios'

export async function getStaticProps() {
    const res = await axios.get(`${process.env.NEXT_PUBLIC_HOST}collections/`);
    const data = res.data;
    return {
        props: {
            data,
        },
    };
}


function collections(props) {
    const [slides, setSlides] = useState([]);
    useEffect(() => {
        const newData = props.data
        setSlides(newData);
    }, [])

    return (
        <>
            <Head>
                <title>Earthie Fashion - Collections</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="row">
                <div className="col-12 h-25" >
                    <Image src={headImg} fill alt='Collections' className={styles.headerImg + ' '} />
                </div>

                <div className="col-12">

                    <div className="container mt-3">
                        <div className="row">
                            {slides.map((slide) => {
                                if (slide.is_published) {
                                    return (
                                        <Link href={`col/${slide.collectionName}`} className="col-12 col-lg-3 col-md-4 col-sm-6 my-3 d-flex justify-content-center my-3">
                                            <div  key={slide.id}>
                                                <CollectionCard productName={slide.collectionName} productImage={slide.collectionImage} />
                                            </div>
                                        </Link>
                                    )
                                }
                            })}
                        </div>
                    </div>
                </div>
            </div>
        </>

    )
}

export default collections