import React, { useEffect } from 'react'
import Head from 'next/head'
import headerImg from '../public/Images/login.png'
import Image from 'next/Image'
import styles from '../styles/Login.module.css'
import { Icon } from '@iconify/react';
import Link from 'next/link'
import axios from 'axios'
import Router from 'next/router'
import { toast } from 'react-toastify';
import { useRouter } from "next/router";
import jwt_decode from "jwt-decode";




function login({ notify }) {

    useEffect(() => {
        if (localStorage.getItem('token')) {
            Router.push('/')
        }
    }, [])

    async function submitForm(e) {
        e.preventDefault();
        const email = document.getElementById('email').value
        const pass = document.getElementById('pass').value
        const data = {
            "email": email,
            "password": pass
        }

        axios.post('http://192.168.0.7:8000/token/', data, {
            headers: {
                'Content-Type': 'application/json'
            }
        })
            .then(response => {
                console.log(response);
                if (response.status == '200') {
                    localStorage.setItem('token', response.data.access)
                    let name = (jwt_decode(response.data.access)).name;
                    notify(toast.success(`👋 Welcome Back ${name}`, {
                        icon: false
                      }))
                    Router.push('/')
                }
            })
            .catch(error => {
                notify(toast.error("Invalid Credentials", { theme: "dark" }))
            });

        console.log('form submitted')



    }


    return (
        <>
            <Head>
                <title>Earthie Fashion - Login</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>


            <div className="row">
                <div className="col-12 h-50 w-100">
                    <Image src={headerImg} className={styles.HeadImage} alt="login image" />
                </div>
            </div>

            <div className={styles.formWrapper + " p-4"}>
                <div className="innerForm">
                    <p className={styles.formHead + "  mb-0"}>
                        Welcome back!
                    </p>
                    <p className={styles.supportText + " mx-1"}>
                        Get back into your account...
                    </p>

                    <form onSubmit={submitForm} className='px-3' >
                        <div className="row">
                            <div className={styles.inputWrapper + " col-12 d-flex align-items-center p-0"}>
                                <Icon icon="clarity:email-line" className={styles.formIcon + ' mx-2'} />
                                <input type="email" id='email' placeholder='harsh@email.com' className={styles.formInputs + " form-control px-0"} />
                            </div>

                            <div className={styles.inputWrapper + " col-12 d-flex align-items-center p-0 mt-3"}>
                                <Icon icon="carbon:password" className={styles.formIcon + ' mx-2'} />
                                <input type="password" id='pass' placeholder='p@ssword1234' className={styles.formInputs + " form-control px-0"} />
                            </div>

                            <div className="col-12 d-flex px-0 mt-3">
                                <Link className={styles.underLinks} href={'/signup'}> <p className={styles.otherLinks + " mb-0"}>Create an account</p></Link>
                                <p className={styles.otherLinks + " mb-0 mx-1"}>|</p>
                                <Link className={styles.underLinks} href={'/forgotPass'}> <p className={styles.otherLinks + " mb-0"}>Forgot Password</p></Link>
                            </div>

                            <div className="col-12 px-0">
                                <button type="submit" className={styles.subBtn + " btn btn-dark w-100 mt-3"}>Login</button>
                            </div>
                        </div>
                    </form>

                    <div className="col-12 d-flex px-0 mt-3">
                        {/* <p className={styles.lastLinks + " d-flex align-items-center"}>&#169;2022 Earthie Fashion</p> */}

                        {/* <div className="d-flex">
                            <Link className={styles.lastLinks} href={'/signup'}> <p className={styles.footLinks + " mb-0"}>Terms & Conditions</p></Link>
                            <p className={styles.lastLinks + " mb-0 mx-1"}>|</p>
                            <Link className={styles.lastLinks} href={'/forgotPass'}> <p className={styles.footLinks + " mb-0"}>Privacy Policy</p></Link>
                        </div> */}
                    </div>
                </div>
            </div>
        </>
    )
}

export default login