import React from 'react'
import Image from 'next/Image'
import Head from 'next/head'
import headImg from '../public/Images/spoffers.png'
import styles from '../styles/NewArrivals.module.css'

function offers() {
    return (
        <>
            <Head>
                <title>Earthie Fashion - Special Offers</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <div className="row">
                    <div className="col-12 h-25" >
                        <Image src={headImg} fill className={styles.headerImg + ' '} />
                    </div>
                </div>
            </div>
        </>
    )
}

export default offers