import React from 'react'
import Head from 'next/head'
import headerImg from '../public/Images/signup.png'
import Image from 'next/Image'
import styles from '../styles/Login.module.css'
import { Icon } from '@iconify/react';
import Link from 'next/link'
import axios from 'axios'
import { toast } from 'react-toastify';
import Router from 'next/router'


function signup({notify}) {
    
    async function submitForm(e) {
        e.preventDefault();
        const name = document.getElementById('name').value
        const email = document.getElementById('email').value
        const phone = document.getElementById('phone').value
        const pass = document.getElementById('pass').value
        const pass1 = document.getElementById('pass1').value
        // const response = await axios.post('/api/submit', formData);
        // console.log(response);
        const data = {
            "name": name,
            "email": email,
            "phone": phone,
            "password": pass
        }
        axios.post('http://192.168.0.7:8000/register/', data, {
            headers: {
                'Content-Type': 'application/json'
            }
        })
            .then(response => {
                console.log(response);
                if (response.status == '201') {
                    notify(toast.success(`Account created for ${response.data.name}`))
                    Router.push('/login')
                }

            })
            .catch(error => {
                console.log(error)
            });
    
        console.log('form submitted')
    
    }
    return (
        <>
            <Head>
                <title>Earthie Fashion - Signup</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="row">
                <div className="col-12 h-50 w-100">
                    <Image src={headerImg} className={styles.HeadImage} alt="login image" />
                </div>
            </div>

            <div className={styles.formWrapper + " p-4"}>
                <div className="innerForm">
                    <p className={styles.formHead + "  mb-0"}>
                        Welcome to Earthie!
                    </p>
                    <p className={styles.supportText + " mx-1"}>
                        Create an account to use our services...
                    </p>

                    <form onSubmit={submitForm} className='px-3' >
                        <div className="row">
                            <div className={styles.inputWrapper + " col-12 d-flex align-items-center p-0 "}>
                                <Icon icon="et:profile-male" className={styles.formIcon + ' mx-2'} />
                                <input type="text" id='name' placeholder='Harsh Lad' className={styles.formInputs + " form-control px-0"} />
                            </div>
                            <div className={styles.inputWrapper + " col-12 d-flex align-items-center p-0 mt-3"}>
                                <Icon icon="clarity:email-line" className={styles.formIcon + ' mx-2'} />
                                <input type="email" id='email' placeholder='harsh@email.com' className={styles.formInputs + " form-control px-0"} />
                            </div>


                            <div className={styles.inputWrapper + " col-12 d-flex align-items-center p-0 mt-3"}>
                                <Icon icon="bi:phone-vibrate" className={styles.formIcon + ' mx-2'} />
                                <input type="tel" id='phone' placeholder='9999999999' className={styles.formInputs + " form-control px-0"} />
                            </div>


                            <div className={styles.inputWrapper + " col-12 d-flex align-items-center p-0 mt-3"}>
                                <Icon icon="carbon:password" className={styles.formIcon + ' mx-2'} />
                                <input type="password" id='pass' placeholder='p@ssword1234' className={styles.formInputs + " form-control px-0"} />
                            </div>

                            <div className={styles.inputWrapper + " col-12 d-flex align-items-center p-0 mt-3"}>
                                <Icon icon="carbon:password" className={styles.formIcon + ' mx-2'} />
                                <input type="password" id='pass1' placeholder='p@ssword1234' className={styles.formInputs + " form-control px-0"} />
                            </div>

                            <div className="col-12 d-flex px-0 mt-3">
                                <Link className={styles.underLinks} href={'/login'}> <p className={styles.otherLinks + " mb-0"}>Already an account</p></Link>
                                <p className={styles.otherLinks + " mb-0 mx-1"}>|</p>
                                <Link className={styles.underLinks} href={'/forgotPass'}> <p className={styles.otherLinks + " mb-0"}>Forgot Password</p></Link>
                            </div>

                            <div className="col-12 px-0">
                                <button type="submit" className={styles.subBtn + " btn btn-dark w-100 mt-3"}>Create account</button>
                            </div>
                        </div>
                    </form>

                    <div className="col-12 d-flex px-0 mt-3">
                        {/* <p className={styles.lastLinks + " d-flex align-items-center"}>&#169;2022 Earthie Fashion</p> */}

                        {/* <div className="d-flex">
                            <Link className={styles.lastLinks} href={'/signup'}> <p className={styles.footLinks + " mb-0"}>Terms & Conditions</p></Link>
                            <p className={styles.lastLinks + " mb-0 mx-1"}>|</p>
                            <Link className={styles.lastLinks} href={'/forgotPass'}> <p className={styles.footLinks + " mb-0"}>Privacy Policy</p></Link>
                        </div> */}
                    </div>
                </div>
            </div>
        </>
    )
}

export default signup